#!/usr/bin/env php
<?php
require_once "vendor/autoload.php";
// bin/doctrine

use Doctrine\ORM\Tools\Console\ConsoleRunner;
use Doctrine\ORM\Tools\Console\EntityManagerProvider\SingleManagerProvider;

// Adjust this path to your actual bootstrap.php
require __DIR__ . '/doctrineTool.php';

ConsoleRunner::run(
    new SingleManagerProvider($entityManager)
);